# Generated by Django 3.0.7 on 2020-07-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_p',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
